I=imread('1.jpg');
[r,c]= size(I);
A=I(1:r/2,1:c/2);
[p,q]=size(A);
          A1=A(1:p,1:q/3);
B=I(1:r/2,c/2+1:c);
[a,b]=size(B);
          B1=B(1:a,1:b/3);
C=I(r/2+1:r,1:c/2);
[e,f]=size(C);
           C1=C(1:e,1:f/3);
D=I(r/2+1:r,c/2+1:c);
[u,v]=size(D);
          D1=D(1:u,1:v/3);
%L=([A1 B;D A]);
subplot(2,2,1), imshow(A1), title('Image changed');
%subplot(3,3,2), imshow(B), title('Image changed');
subplot(2,2,2), imshow(B1), title('Image changed');
%subplot(3,3,4), imshow(C), title('Image changed');
subplot(2,2,3), imshow(C1), title('Image changed');
%subplot(3,3,6), imshow(D), title('Image changed');
subplot(2,2,4), imshow(D1), title('Image changed');